services:
  # --- Gateway (Nginx) ---
  # Centraliza todas as chamadas do frontend para os backends
  gateway:
    build: ./services/gateway
    ports:
      - "${PORT_GATEWAY}:80"
    depends_on:
      - patrimonio-service
      - emprestimo-service
    networks:
      - almoxarifado-net

  # --- Serviço de Patrimônio ---
  postgres-patrimonio:
    image: postgres:15
    environment:
      POSTGRES_DB: patrimonio
      POSTGRES_USER: patrimonio_user
      POSTGRES_PASSWORD: patrimonio_pass
    volumes:
      - postgres_patrimonio_data:/var/lib/postgresql/data
      - ./services/patrimonio-service/schema_patrimonio.sql:/docker-entrypoint-initdb.d/schema_patrimonio.sql
    networks:
      - almoxarifado-net


  patrimonio-service:
    build: ./services/patrimonio-service
    depends_on:
      - postgres-patrimonio
    ports:
      - "3001:3001"
    networks:
      - almoxarifado-net

  # --- Serviço de Empréstimo/Estoque ---
  emprestimo-service:
    build: ./services/emprestimo-service
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_EMPRESTIMO_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    ports:
      - "${PORT_EMPRESTIMO}:${PORT_EMPRESTIMO}"
    networks:
      - almoxarifado-net

  # --- Frontend (React/Vite) ---
  frontend:
    build: ./frontend
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    environment:
      - VITE_API_URL=http://localhost:${PORT_GATEWAY}
    networks:
      - almoxarifado-net

networks:
  almoxarifado-net:
    driver: bridge


volumes:
  postgres_patrimonio_data:
