server {
    listen 80;

    # Redireciona chamadas de Patrimônio
    location /api/patrimonio/ {
        proxy_pass http://patrimonio-service:3001/;
    }

    # Redireciona chamadas de Empréstimo
    location /api/emprestimo/ {
        proxy_pass http://emprestimo-service:3002/;
    }

    # Redireciona o restante para o Frontend
    location / {
        proxy_pass http://frontend:5173/;
    }
}